language: python
python:
- 3.6
env:
  global:
  - MONGO_DB_NAME=debug MONGO_DB_COLLECTION=debug_todo MONGO_DOMAIN=localhost MONGO_HEROKU=heroku
    MONGO_PASS=password MONGO_PORT=12345 MONGO_USER=user
install:
- make init
script:
- make lint
- make test
deploy:
  provider: heroku
  api_key:
    - secure: djWDwBDGvHb9b8oeqkEz4aCv9vOsTTouwP0FQQQG3QbmHyjx+RIlu4GeeO2O+VOs0SaubAWtxa0ucjBU9ri8K/7Cx8BgGJTcSKrk0BBCmBS1fu27F/MqAG6MvCi1Pz1SJBHlRa3yh3FRkfB6dAbz89rrI4FLdC/9gzNsA+fV/Ueg5mJOL7ln8XuuRnbirKU98acvBWYy1/+7qQVBbKE57PmwCKf6k7hWlz4StPw5Qney/L6FcfYhBiqJ+VaXXD1HLTyc7SUHSrYY0Km119vuuyUJqqQWiWWPg91upAgASmNRPJ5AgWlFTAWF1nYkvhs9twUURGBbgK+q+WiVv2fn0C5O57YHyLnszP98aPt1OEn3e7DSSgwPsfgCB1oZaFK5ro5bp6wIYPRNza/oxOjHaIfaxyuBSH/OxjfXcWtTf4tGD7sUwPakUAKDcodx88vL4KqLGjnA5RpEnqw6bAgVjmXgpoZroaX8oQQus/SoUtbYbffa3KR3I+LuZmU0gjSDFd+jMALVKqga8NfIaw5gQ/cdZ3LlHrmL3tNB6Pa8oo4D5yz97Q8YInEXszMyYaPvq7T3COEYynKHxf7WydZml7toqYJ6lgb0/e1UqwanqmbmfW/fyFR1g6u4YJa+wbCKYasrTgy67jN6HIKx1UtmJZOSzggdJFnao/P3iWX0tTA=
  app: nameless-inlet-33375
