language: python
python:
- 3.6
env:
  global:
  - MONGO_DB_NAME=debug MONGO_DB_COLLECTION=debug_todo MONGO_DOMAIN=localhost MONGO_HEROKU=heroku
    MONGO_PASS=password MONGO_PORT=12345 MONGO_USER=user
install:
- make init
script:
- make lint
- make test
deploy:
  provider: heroku
  api_key:
    secure: iz6pAbSw5WzlhgEo36zLoviKQw/RCQSNi+/uV9v/2kJHMkpnRru8JYCtiAjYd2Z5fJs6AtaZKhFFFb1Mth6E4Njkjkak6RUvdwOppn4PLYG8TnPbeviLNPSkpnLU4MGsLYcfgIc3bHaQovfU9apZEEyAPF9fETsfWJAgYANXvdFqK/5t8FqAN7D1qTPNxqTanMn4TjHVlg+PQswet17rrsj39kw0OvirX6MHIulg1LSTWmRajYAe9VZpzkoqI41xp2rB1F5yn5yY8TG/0BBxeQmkTTzR9T4J3/v622euDQYp3ull6jedajYyweak+JqTbXqcP8YGEiCJQYhnTwvEFi7BQS2nSnrXb2B4UamqFBxe2Qa3JSooE5lFDqLfatt0GDQ91IPj1jovWt6rKhEWLrbZg3zDXnGnyGln4OVx9YqD1OWrhBTthr9h17LhBUoHLqdUzPRQTP6JHR+eFmaF6QeZmzpsTW/9NiUPfRgX4wuTefFCwfspph8xHOtw+BuIsOBwC3c5tRM+EMpOePluzEwrWsc+nsoPW286TfnsdHzTdhGgfq1WbP2erf4hpQmMgPR2aalXZJSk65Lc3N7391gSPX1AUPCYc9b5nr8q18p6RU9VNs9kEUAtBj7W2UGM2ND4QhAm/ilj0WlikJMxIfeu+iA26aGQdjZ0n0W3gAo=
  app: nameless-inlet-33375
